language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "hhvm" ]; then composer require --prefer-source "doctrine/dbal"="2.5.*@dev" "doctrine/doctrine-bundle"="1.3.*@dev"; fi;'
  - composer install --prefer-source
  - app/console doctrine:database:create -e=test
  - app/console doctrine:phpcr:init:dbal -e=test
  - app/console doctrine:phpcr:workspace:create standard_test -e=test
  - app/console doctrine:phpcr:repository:init -e=test

script: phpunit -c app

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
